image: 3.7.2-alpine3.9

stages:
  - test

unit-tests:
  stage: test
  script:
    - pytest --ignore=setup.py --cov=./ --cov-branch
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

integration-tests:
  stage: test
  script:
    - echo Hello
