  language: python
  python:
    - "3.5"
    - "nightly"
  install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
  script:
    - pytest
    - codecov --token=6b5d0835-8dcf-4847-bc72-d2659d84dc22